/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hands_on;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        WolrdTime classUnderTest = new WolrdTime();
        assertNotNull(classUnderTest.getTimeByCountry("America/New_York"), "app should have a greeting");
    }
}
