/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hands_on;

import org.joda.time.*;
import org.joda.time.format.DateTimeFormat;

public class WolrdTime {
    public String getTimeByCountry(String local) {
       // Calendar calendar = Calendar.getInstance();
       // calendar.setTime(new Date());

       
        DateTimeZone zone = DateTimeZone.forID(local);

       // SimpleDateFormat sdf = new SimpleDateFormat("hh:mm");

       // sdf.setTimeZone(TimeZone.getTimeZone(zone.toString()));

       org.joda.time.format.DateTimeFormatter fmt = DateTimeFormat.forPattern("HH:mm");
       DateTime dt = new DateTime(zone);
       
       return fmt.print(dt);
        // .format ("HH:mm")
    }

    public static void main(String[] args) {
      WolrdTime wt = new WolrdTime();
        System.out.println(wt.getTimeByCountry("America/Adak"));
    }

}
